model_output_path: data/07_model_output/autogluon_model

hyperparameters:
  GBM:
      extra_trees: True
      learning_rate: 0.05
      num_boost_round: 3000
      max_depth: 10
      subsample: 0.8
      colsample_bytree: 0.8
  CAT:
      iterations: 3000
      learning_rate: 0.05
      depth: 8
  RF: {}
  XT: {}
  NN_TORCH: {}